In [7]:
import numpy as np

board_game = np.array([[3, 2, 3], [2, 4, 2], [3, 2, 3]])
indices = {0, 1, 2}

line0 = board_game[0]
line1 = board_game[1]
line2 = board_game[2]

col0 = board_game[:,0] # Référence à la colonne 0
col1 = board_game[:,1]
col2 = board_game[:,2]

# diag1 = [board_game[0][0], board_game[1][1], board_game[2][2]]
# diag2 = [board_game[0][2], board_game[1][1], board_game[2][0]]

diag1 = board_game.diagonal()
diag2 = np.fliplr(board_game).diagonal()

if 8 in line0:
    print("8 is in ligne1")

if 3 in line0:
    print("3 is in ligne1")

print(board_game)
board_game[2][2] = 1024
print(board_game)
print(line2)
print(col2)
print(diag1)

3 is in ligne1
[[3 2 3]
 [2 4 2]
 [3 2 3]]
[[   3    2    3]
 [   2    4    2]
 [   3    2 1024]]
[   3    2 1024]
[   3    2 1024]
[   3    4 1024]


In [ ]:
board_game = [[3, 2, 3], [2, 4, 2], [3, 2, 3]]
my_max = max(board_game)
my_max

In [ ]:
import numpy as np
import time

# Generate a large 1000x1000 random matrix
np.random.seed(42)
board_game = np.random.randint(0, 1000, size=(3, 3)).tolist()

# Method 1: Using max(map(max, board_game)) + next()
start_time = time.time()
max_value = max(map(max, board_game))
max_indices = next((i, row.index(max_value)) for i, row in enumerate(board_game) if max_value in row)
time_method_1 = time.time() - start_time
print(max_indices[0], max_indices[1])

# Method 2: Using nested loops
start_time = time.time()
max_value = -1
y, x = -1, -1
for j in range(len(board_game)):
    for i in range(len(board_game[0])):
        if board_game[j][i] > max_value:
            max_value = board_game[j][i]
            y, x = j, i
time_method_2 = time.time() - start_time

# Display results
time_method_1, time_method_2

# 1000x1000 matrix (0.019032716751098633, 0.08292317390441895)
# 3x3 matrix (0.0000011920928955078125, 0.0000011920928955078125)



In [12]:
import numpy as np
board_game = np.array([[3, 2, 3], [2, 4, 2], [3, 1024, 3]])
max_indices = np.argwhere(board_game == board_game.max())[0]
print(max_indices[0], max_indices[1])


2 1


In [ ]:
import sys
import numpy as np  # available on coding game

k_opponent = -1
# board_game = np.array([[3, 2, 3], [2, 4, 2], [3, 2, 3]])
board_game = np.array([[-1, 1, 2], [-1, -2, 1], [-2, 2, 2]])

line0 = board_game[0]
line1 = board_game[1]
line2 = board_game[2]

col0 = board_game[:, 0]  
col1 = board_game[:, 1]
col2 = board_game[:, 2]

diag1_indices = np.arange(board_game.shape[0])  # [0, 1, 2]
diag2_indices = np.arange(board_game.shape[0])[::-1]  # [2, 1 ,0] 
def update_board_game(opp_row, opp_col):
    if opp_row == -1 and opp_col == -1:
        print(f"Board at init         : {board_game}", file=sys.stderr, flush=True)
    else:
        # Si dans la opp_col il n'y a pas de k_opponent alors on enlève 1 aux cellules dont la valeur est > 0
        if k_opponent not in board_game[:, opp_col]:
            board_game[:, opp_col] -= (board_game[:, opp_col] > 0).astype(int)  # astype convert bool to int
        
        if k_opponent not in board_game[opp_row]:
            board_game[opp_row] -= (board_game[opp_row] > 0).astype(int)  # astype convert bool to int
        
        # Si k_opponent n'est pas dans la diagonale principale
        if (opp_row==opp_col) and k_opponent not in board_game[diag1_indices, diag1_indices]:
            board_game[diag1_indices, diag1_indices] -= (board_game[diag1_indices, diag1_indices] > 0).astype(int)

        # Si k_opponent n'est pas dans la diagonale secondaire
        if (opp_row==2-opp_col) and k_opponent not in board_game[diag2_indices, diag1_indices]:
            board_game[diag2_indices, diag1_indices] -= (board_game[diag2_indices, diag1_indices] > 0).astype(int)


        board_game[opp_row][opp_col] = k_opponent
        print(f"Board after opponent  :\n{board_game}", file=sys.stderr, flush=True)
    return

print(f"Board before opponent  :\n{board_game}", file=sys.stderr, flush=True)
update_board_game(0, 0)

Board before opponent  :
[[3 2 3]
 [2 4 2]
 [3 2 3]]
Board after opponent  :
[[-1  1  2]
 [ 1  3  2]
 [ 2  2  2]]


In [16]:
board_game = np.array([[-1, 1, 2], [-1, -2, 1], [-2, 2, 2]])
max_indices = np.argwhere(board_game == board_game.max())[0]
print(max_indices[1], max_indices[0])
print(f"Board after selection : {board_game}", file=sys.stderr, flush=True)



Board after selection : [[-1  1  2]
 [-1 -2  1]
 [-2  2  2]]


2 0


In [17]:
board_game = np.array([[-1, 1, 2], [-1, -2, 1], [-2, 2, 2]])

max_value = -100
for j in range(3):
    for i in range(3):
        if board_game[j][i] > max_value:
            max_weight = board_game[j][i]
            y = j
            x = i
print(y, x)


2 2
